[gpg]
  pubkey_url = "https://kerembozdas.com/pubkey.asc"
  fingerprint = "1B01B3C4EEFBE1730136D89338FD2B3F677F9C34"
[git.init]
  default_branch = "master"
[git.user]
  name = "Kerem Bozdas"
  email = "krmbzds.github@gmail.com"
  signing_key = "38FD2B3F677F9C34"
[git.commit]
  gpgsign = "true"
[git.delta]
  syntax_theme = "Dracula Pro"
[prefs]
  somafm = true
  dracula_pro = true
  browser_hw_accel = true
[prefs.nvim]
  telescope = true
[dependencies]
  rvm = true
  anki = true
  faas = true
  meld = true
  docker = true
  devops = true
  newsboat = true
  sublime_text = true
  brave_browser = true
  signal_messenger = true
  ungoogled_chromium = true
[pulseaudio]
  switch_on_connect = false
[gnome]
  dracula = true
  workspace_count = 4
  static_workspaces = true
  workspace_indicator = true
  workspace_switcher_popup = false
[logitech.g213]
  enabled = true
  remap_caps_lock = true
  custom_backlight = true
  backlight_color = "22212C"
  device_name = "Logitech Gaming Keyboard G213"
