[gpg]
pubkey_url = "https://kerembozdas.com/pubkey.asc"
fingerprint = "1B01B3C4EEFBE1730136D89338FD2B3F677F9C34"

[git.init]
default_branch = "master"

[git.user]
name = "Kerem Bozdas"
email = "krmbzds.github@gmail.com"
signing_key = "38FD2B3F677F9C34"

[git.commit]
gpgsign = "true"

[prefs]
editor = "nvim"
visual = "nvim"
dracula_pro = true
dracula_pro_url = "https://github.com/krmbzds/dracula-pro"

[fonts]
antialiasing = true
antialiasing_type = "subpixel"
hinting = true
hintstyle = "hintslight"
lcdfilter = "lcddefault"
font_mscore = true
font_croscore = true
font_crosextra = true
font_source_code_pro = true

[dependencies]
anki = true
zeal = true
faas = true
meld = true
brave = true
broot = true
geary = false
totem = false
docker = true
evince = false
flatpak = true
newsboat = true
difftastic = true
libreoffice = false
taskwarrior = true
sublime_text = false
simple_scanner = false
signal_messenger = true

[gnome]
dracula = true
enable_animations = false
logout_prompt = false
natural_scroll = true
static_workspaces = true
workspace_count = 4

[gnome.mutter]
center_new_windows = true
center_window = "<Super>c"

[gnome.dash_to_dock]
autohide = true
position  = "LEFT"

[gnome.pop_cosmic]
show_application_menu = false
show_workspaces_button = false
workspace_picker_left = true

[asdf]
enabled = true
lua = true
ruby = true
rust = true
yarn = true
golang = true
nodejs = true
python = true
fd = true
jq = true
xh = true
bat = true
duf = true
exa = true
dust = true
helm = true
tmux = true
vale = true
cheat = true
delta = true
doctl = true
viddy = true
neovim = true
stylua = true
kubectl = true
lazygit = true
ripgrep = true
terraform = true
lazydocker = true
shellcheck = true
github_cli = true

[logitech.mx_anywhere_2s]
enabled = true
dpi = 400
device_name = "Anywhere 2S"

[skyloong.gk61x]
enabled = true
remap_caps_lock = true
remap_shift = false
device_link = "/dev/input/by-id/usb-SEMITEK_USB-HID_Gaming_Keyboard_SN0000000001-event-kbd"

[ledger.nano_s]
enabled = true
